= OCP Secrets Retrieval with Apache Camel Kubernetes Component
:icons: font
:numbered:
:title: OCP Secrets Retrieval with Apache Camel Kubernetes Component
:toc: left
:toclevels: 2
:source-highlighter: coderay

== Context

Kubernetes Secrets are usually used to store and manage sensitive data, such as API keys, passwords, and tokens, within a Kubernetes cluster. They help keep this information secure by avoiding hardcoding it in configuration files. Secrets can be injected into containers or read at runtime, ensuring that sensitive data are only accessible to authorized services or pods. 

== Prerequisites 

A camel integration to be deployed on https://www.redhat.com/en/technologies/cloud-computing/openshift[**OpenShift**].

== Goal

Provide a configuration example to read kubernetes secrets values in camel applications.

== Configuration
In Camel we provide the secret function to retrieve secret value from a secret resource.

The syntax is pretty simple:

....
secret:name/key[:defaultValue]
....

It’s important to restrict the ability to read secret with the least amount of permissions for your cluster. So the application should run with a role with only list/read secrets permission.

This could be done with the following command:

....
oc create clusterrole secretadmin --verb=get --verb=list --resource=secret --namespace=<namespace>
....

The minimum permissions are list and get.

Alternatively, you can create a yaml file with the following content:

[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretadmin
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
----

And then run 

....
oc apply -f <file_name>
....

The application will have to run with that clusterrole.

This will ensure the running application won’t be able to do more than list and get secrets.

The same configuration could be seen on OCP by following the Camel on
OCP Best Practices repository, in particular, the OCP Secrets section. You
can follow the example for both the runtimes supported by Red Hat Build
of Apache Camel:

https://github.com/jboss-fuse/apache-camel-on-ocp-best-practices/tree/main/examples/ocp/secrets/camel-quarkus/retrieval[Camel-Quarkus
- Camel on OCP Best practices - Camel Quarkus - Secrets Retrieval]

https://github.com/jboss-fuse/apache-camel-on-ocp-best-practices/tree/main/examples/ocp/secrets/camel-spring-boot/retrieval[Camel-Spring-Boot
- Camel on OCP Best practices - Camel Spring Boot - Secrets Retrieval]

