name: Check pull requests

on:
  pull_request:
    branches-ignore: [ gh-pages ]

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: Asciidoctoring the docs to pretty HTML!
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get build container
      id: adocbuild
      uses: rhpds/asciidoctor-action@master
      with:
          program: "asciidoctor -D public/ --backend=html5 docs/*.adoc"

    - name: Rename README.html to index.html
      run: sudo mv public/README.html public/index.html

    - name: Copy asset folder to public/ dir
      run: sudo cp -r docs/assets/ public/

    - name: Print execution time
      run: echo "Time ${{ steps.adocbuild.outputs.time }}"

    - name: Archive generated site
      uses: actions/upload-artifact@v4
      with:
        name: docs-preview
        path: public/
